### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by imanghafoori1**
posible is changed to possible.

### CODE REVIEW

**Comment by lookitsatravis** [comment]
Hi there. I see you're making a lot of changes to this project. I wanted to make you aware that I will not be accepting any refactoring PRs for version 1.x at this time - only bug fixes. I have no plans to make changes to the base functionality, and I've been slowing working a version 2 rewrite. If you'd like to continue doing a refactor, then by all means keep a fork and have at it! Otherwise, you can expect a version 2 release some time in Q1 2019.

**Comment by imanghafoori1** [comment]
Nice, Good Luck

**Comment by imanghafoori1** [comment]
I was refactoring the code during a video series tutorial to show some useful techniques.

**Comment by lookitsatravis** [comment]
Wow, man. I can't tell if you're being intentionally insulting or not. I know that this code is MIT licensed, but I would encourage you to think long and hard about whether or not it's a good and positive idea to take someone else's code and publicly use it as an example of bad code which needs refactoring. Especially without giving the courtesy of permission or even a heads up. As licensed, you can do whatever you want, but from a "good person" point-of-view, please consider writing your own example and not calling out someone else.

This code is over 5 years old at a time when I was learning Laravel and PHP standards, and to be honest it could use some love. As such, my refactor effort is much more in line with best practices (in general and for PHP).

I would ask that you do not use this codebase and my name (which is personally identifying) in your efforts to point out bad code. It could have any number of unforeseen consequences for me personally, all stemming from my effort to add something to the community at a time when I was still learning about it.

**Comment by imanghafoori1** [comment]
Do not worry about nad reputition man. Since
1 - the video is in persian language and limited in only one country. In fact very few people are watching my vids.
2 - I have told them that this package is very well tested and bug free and the best one they can find for sorting. And encouraged them to use it. The problems mention are internal to the package. They are not bugs.

**Comment by imanghafoori1** [comment]
Anyway I am teaching them how to contribute to open source on github.
Some real world example was needed.

Anyway sorry for that.
It is not an insult.

**Comment by lookitsatravis** [comment]
Fair enough, @imanghafoori1. I had hoped there was no ill-will meant, so thank you for clarifying. If you're okay with it, I will delete all of the comments that are part of my misunderstanding.

**Comment by imanghafoori1** [comment]
Of course. Delete them all

**Pull request closed without merging**
